In [199]:
# 加载数据
data = open('data/nietzsche.txt', encoding='utf-8').read()
data = data.replace('\n', '').replace('\r', '')
print(data)

hello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello world


In [200]:
# 字符去重
letters = list(set(data))
print(letters)

print("\n")

num_letters = len(letters)
print(num_letters)

['r', ' ', 'd', 'e', 'w', 'h', 'o', 'l']


8


In [201]:
# 建立字典
int_to_char = {i: c for i, c in enumerate(letters)}
print(int_to_char)

print("\n")

char_to_int = {c: i for i, c in enumerate(letters)}
print(char_to_int)

{0: 'r', 1: ' ', 2: 'd', 3: 'e', 4: 'w', 5: 'h', 6: 'o', 7: 'l'}


{'r': 0, ' ': 1, 'd': 2, 'e': 3, 'w': 4, 'h': 5, 'o': 6, 'l': 7}


In [202]:
time_step = 100

In [203]:
import numpy as np
from keras.utils import to_categorical


def extract_data(data, slide):
    """
    滑动窗口提取数据
    :param data: 
    :param slide: 
    :return: 
    """
    x = []
    y = []

    for i in range(len(data) - slide):
        x.append([a for a in data[i:i + slide]])
        y.append(data[i + slide])
    return x, y


def char_to_int_data(x, y, char_to_int):
    """
    字符转数字
    :param x: 
    :param y: 
    :param char_to_int: 
    :return: 
    """
    x_to_int = []
    y_to_int = []

    for i in range(len(x)):
        x_to_int.append([char_to_int[c] for c in x[i]])
        y_to_int.append([char_to_int[c] for c in y[i]])
    return x_to_int, y_to_int


def data_preprocessing(data, slide, num_letters, char_to_int):
    """
    数据预处理
    :param data: 
    :param slide: 
    :param num_letters: 
    :param char_to_int: 
    :return: 
    """
    chart_data = extract_data(data, slide)
    int_data = char_to_int_data(chart_data[0], chart_data[1], char_to_int)
    Input = int_data[0]
    Output = list(np.array(int_data[1]).flatten())
    Input_RESHAPED = np.array(Input).reshape(len(Input), slide)
    new = np.random.randint(0, 10, size=[Input_RESHAPED.shape[0], Input_RESHAPED.shape[1], num_letters])
    for i in range(Input_RESHAPED.shape[0]):
        for j in range(Input_RESHAPED.shape[1]):
            new[i, j, :] = to_categorical(Input_RESHAPED[i, j], num_classes=num_letters)

    return new, Output

In [204]:
x, y = data_preprocessing(data, time_step, num_letters, char_to_int)

print(x, "\n", len(x), "\n", x.shape)
print(y, "\n", len(y))

[[[0 0 0 ... 1 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 1]
  ...
  [0 0 0 ... 0 0 1]
  [0 0 1 ... 0 0 0]
  [0 0 0 ... 1 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 1]
  [0 0 0 ... 0 0 1]
  ...
  [0 0 1 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 1]
  [0 0 0 ... 0 0 1]
  [0 0 0 ... 0 1 0]
  ...
  [0 0 0 ... 1 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 1]]

 ...

 [[0 0 0 ... 0 1 0]
  [1 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 1]
  ...
  [0 1 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 1 0]]

 [[1 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 1]
  [0 0 1 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 1 0]
  [1 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 1]
  [0 0 1 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  ...
  [0 0 0 ... 0 1 0]
  [1 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 1]]] 
 32 
 (32, 100, 8)
[3, 7, 7, 6, 1, 4, 6, 0, 7, 2, 5, 3, 7, 7, 6, 1, 4, 6, 0, 7, 2, 5, 3, 7, 7, 6, 1, 4, 6, 0, 7, 2] 
 32


In [205]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=10)

print(x_train.shape, len(y_train))

(28, 100, 8) 28


In [206]:
y_train_category = to_categorical(y_train, num_letters)
print(y_train_category)

[[0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


In [207]:
from keras import Input
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(Input((x_train.shape[1], x_train.shape[2])))
model.add(LSTM(units=20, activation='relu'))
model.add(Dense(units=num_letters, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_11 (LSTM)                  │ (None, 20)             │         2,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 8)              │           168 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,488 (9.72 KB)

 Trainable params: 2,488 (9.72 KB)

 Non-trainable params: 0 (0.00 B)

In [208]:
model.fit(x_train, y_train_category, epochs=100, batch_size=1000)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.0714 - loss: 2.0887
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.0714 - loss: 2.0852
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0714 - loss: 2.0819
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.0714 - loss: 2.0786
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.0714 - loss: 2.0754
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.0714 - loss: 2.0723
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.0714 - loss: 2.0692
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.0714 - loss: 2.0662
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.0714 - loss: 2.0633
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.0000e+00 - loss: 2.0604
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 2.0576
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.000

In [209]:
# y_train_predict = model.predict_classes(x_train)
# print(y_train_predict)

predict_y=model.predict(x_train)
y_train_predict=np.argmax(predict_y,axis=1)
print(y_train_predict)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [210]:
y_train_predict_char = [int_to_char[i] for i in y_train_predict]
print(y_train_predict_char)

['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l']


In [211]:
from sklearn.metrics import accuracy_score

accuracy_train = accuracy_score(y_train, y_train_predict)
print(accuracy_train)

0.2857142857142857


In [212]:
# y_test_predict = model.predict(x_test)

predict_x=model.predict(x_test)
y_test_predict=np.argmax(predict_x,axis=1)

accuracy_test = accuracy_score(y_test, y_test_predict)

print(accuracy_test)
print(y_test_predict)
print(y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step
0.25
[7 7 7 7]
[2, 0, 4, 7]


In [213]:
new_letters = 'He obtained his phd in Astralia.'
x_new, y_new = data_preprocessing(data, time_step, num_letters, char_to_int)

# y_new_predict = model.predict(x_new)

predict_yy=model.predict(x_new)
y_new_predict=np.argmax(predict_yy,axis=1)

print(y_new_predict)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [214]:
y_new_predict_char = [int_to_char[i] for i in y_new_predict]
print(y_new_predict_char)

['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l']


In [215]:
for i in range(0, x_new.shape[0] - 20):
    print(new_letters[i:i + 20], "-->",y_new_predict_char[i])

He obtained his phd  --> l
e obtained his phd i --> l
 obtained his phd in --> l
obtained his phd in  --> l
btained his phd in A --> l
tained his phd in As --> l
ained his phd in Ast --> l
ined his phd in Astr --> l
ned his phd in Astra --> l
ed his phd in Astral --> l
d his phd in Astrali --> l
 his phd in Astralia --> l
